name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: run-tests
    env:
      E2E_BASE_URL: ${{ vars.BUILD_E2E_BASE_URL }}
      SOCKET_URL: ${{ vars.BUILD_SOCKET_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup project
        run: yarn start
      - name: Run Playwright tests
        run: yarn tests
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
